---
- name: Add repository key
  apt_key:
    url: "{{ cephclient_debian_repository_key }}"
  become: true
  when: cephclient_configure_repository|bool

- name: Add repository
  apt_repository:
    repo: "{{ cephclient_debian_repository }}"
    state: present
    update_cache: yes
  become: true
  when: cephclient_configure_repository|bool

- name: Install required packages
  apt:
    name: "{{ cephclient_debian_packages }}"
    state: present
  become: true

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  become: true
  loop:
    - src: ceph.conf.j2
      dest: "/etc/ceph/ceph.conf"

- name: Copy keyring file
  copy:
    content: "{{ cephclient_keyring }}"
    dest: "/etc/ceph/ceph.{{ cephclient_keyring_name }}.keyring"
    owner: root
    group: root
    mode: 0600
  become: true
